[font]
  size = 14
  bold = { family = "ubuntumono nerd font", style = "Bold"}
  bold_italic = { family = "ubuntumono nerd font", style = "Bold Italic"}
  italic = { family = "ubuntumono nerd font", style = "Italic" }
  normal = { family = "ubuntumono nerd font", style = "Regular"}

[colors]
  draw_bold_text_with_bright_colors = true
  primary = {foreground = "#FFFFFF", background = "#2B2B2B"}

[colors.normal]
  black = "#555753"
  red = "#EF2929"
  green = "#8AE234"
  yellow = "#FCE94F"
  blue = "#729FCF"
  magenta = "#AD7FA8"
  cyan = "#34E2E2"
  white = "#EEEEEC"

[colors.bright]
  black = "#555753"
  red = "#EF2929"
  green = "#8AE234"
  yellow = "#FCE94F"
  blue = "#729FCF"
  magenta = "#AD7FA8"
  cyan = "#34E2E2"
  white = "#EEEEEC"

[selection]
  save_to_clipboard = true

[cursor]
  style = { shape = "Block", blinking = "On" }

[mouse]
  hide_when_typing = true

[window]
  dimensions = { columns = 80, lines = 24 }
  decorations_theme_variant = "Dark"

[keyboard]
  bindings = [
    {key = "F11", action = "ToggleFullscreen"},
  ]

